config/routes.rb
Rails.application.routes.draw do
  resources :reminders
  devise_for :users, controllers: { sessions: 'users/sessions' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, :description, :month_day

  scope :not_dispatched, -> do
    where('month_day <= ? AND time <= ? AND (last_reminder_sent < ? OR last_reminder_sent IS NULL)', Date.today.day, Time.now, DateTime.now)
  end

  def dispatched?
    month_day <= Date.today.day && last_reminder_sent.present? && last_reminder_sent.month == Date.today.month
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :reminders

  validates_presence_of :email
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, only: [:show, :edit, :update, :destroy]

  def index
    @reminders = current_user.reminders.all
  end

  def show
  end

  def new
    @reminder = Reminder.new
  end

  def edit
  end

  def create
    @reminder = current_user.reminders.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_reminder
    @reminder = Reminder.find(params[:id])
  end

  def reminder_params
    params.require(:reminder).permit(:title, :description, :month_day, :time)
  end

  def authorize!
    ReminderPolicy.new(current_user, @reminder).can?(params[:action]) do |message|
      render json: { error: message }, status: :forbidden
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reminders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reminders/_form.html.erb
<%= form_with(model: reminder, local: true) do |form| %>
  <% if reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :month_day %>
    <%= form.number_field :month_day %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reminders</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Month day</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.title %></td>
        <td><%= reminder.description %></td>
        <td><%= reminder.month_day %></td>
        <td><%= reminder.time %></td>
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @reminder.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reminder.description %>
</p>

<p>
  <strong>Month day:</strong>
  <%= @reminder.month_day %>
</p>

<p>
  <strong>Time:</strong>
  <%= @reminder.time %>
</p>

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>